### PR TITLE
Fix makefile

### PR DESCRIPTION
**Pull request by grant2258**
@arcadez2003 can you pull this into the main repo it fixes the make file to remove duplicate files. So all them files dont need to be renamed like they where before. Unless you update your repo I cant pull it there because its a bit behind

I dont think the person porting this realized you could do this else they would have. It makes port a lot easier in the long run and will fix any dupes itself instead of giving linking errors. 

There is also a fix for the windows debug build (a few inlines needed changed to static)  so i can look at whats going on in windows with the n8080 driver. its the fix_makefile branch on my repo.

all that was done was a 

rename _machine '' *.c
rename _vidhrdw '' *.c
rename _sndhrdw '' *.c

and remove the _extentions from the makefile.common 

then simply point to the new list with no dulpicates

https://github.com/grant2258/mame2003-plus-barcade/blob/61ad5879ef39a2141a3fd36835ae45ab438eef81/Makefile#L630

that is created here
https://github.com/grant2258/mame2003-plus-barcade/blob/61ad5879ef39a2141a3fd36835ae45ab438eef81/Makefile.common#L2706

is only a two line fix and the files renamed and makes porting a lot easier

the windows debug fixes are here
https://github.com/grant2258/mame2003-plus-barcade/commit/61ad5879ef39a2141a3fd36835ae45ab438eef81

### CODE REVIEW

**Comment by arcadez2003** [comment]
@grant2258 im gonna be honest with ya here straight up as they say :) i cannie be assed with this
anymore it filled a wee gap in my day but im getting back into gaming now and as such i wont
have much in the way of time to work on the MAME2003+ core.

That's not to say i wont look at taking on the odd fix on the MAME side here and there but
essentially im edging out the door it's just of late i've allowed myself to be pulled back in
so to speak :)

The second problem here as you know i could never get my head around the git nor could
could i be assed learning so while guys like yourself can do multi-commits via commandline
or PC git tools here i am pasting in one file at a time,  i cant push and merge this as it wants
it done via the commandline and i dont know how to do it

i've enjoyed working with you and the rest of the fellas but all good things must come to the
proverbial end, i'll still be around on the Rpi forums if you wanna point out a fix or two you've 
done which might be a nice addition to the MAME2003+ core it just depends on how many
files i have to paste in ;)

I'll see ya around bigman take it easy!!!

**Comment by grant2258** [comment]
aye nae bova mate was under the impression you where working on it. If i see wee fixes will let you know on the forums tae

**Comment by arcadez2003** [comment]
Aye i was more or less done until someone mentioned Space Launcher :) 

The n8080 games were a target of mine i never quite got around to, so thought fuck it why not do em, but im wanting to reduce my workload here so i'll be keeping a low profile for the next while
so i dont get roped into something else ;)

PS it was you mark that put the 2003+ core on the map until you guys jumped on board it was just 
a wee branch that hardly anyone knew about let alone used, mark doesn't keep to well at the moment and with you booted off the team it's hard for me to keep things going on my own as i tend to only work on the MAME side and that's only half a core where as it was you guys who fixed up alotta problems on the libretro side.

Hence i've had to ask you for help with certain things of late, which i dont like to do as i know your busy plus i know your not to keen to touch base with code that falls on the RA side of the fence.
anyway you know what im like i say im done one min then i'll be bugging ya about some fix the
next :)

I'll catch ya down the road im sure, until then take it easy

**Comment by grant2258** [comment]
not a problem mate yeap my and libretro dont see eye to eye. Never will be happy to not convey an opinion or be silenced, Its safe to say id rather walk over blazing coals than help them profit mongers. Anyway wont say much else on that was a nice while it lasted all good things come to an end. Anything none libretro is fair game other older cores can benefit as well that way.

**Pull request closed without merging**
