### PR TITLE
nds fix tested workin

### PR DESCRIPTION
**Pull request by grant2258**
your branch is a little behind master on libretro dont know if this will merge properly

### CODE REVIEW

**Comment by arcadez2003** [comment]
Yesh i dont update my branch really,to be on the safe side i'll likely just add your fixes directly
i take it this the all important commit..............

https://github.com/arcadez2003/mame2003-plus-libretro/pull/2/commits/7fdd6bdf7cfeb63252e590e806b7ddc6fd0da404

Thanks for taking the time to look at this

**Comment by grant2258** [comment]
yea that the only commit added should work fine .

**Comment by arcadez2003** [comment]
All good thanks again

**Comment by grant2258** [comment]
nae bother seen the thread on reddit.

**Pull request closed without merging**
